### ISSUE TITLE
Разный стиль нейминга

### ISSUE THREAD

**Issue by scffs** [JetBrain2056/Eva#13]
https://github.com/JetBrain2056/Eva/blob/202753af2fa2a400847afc20c929bdc7469bfa1d/views/common.js#L56-L60

Возможно, следует переименовать переменную
```js 
const input_Cpassword
```

Я бы всё вообще делал через `camelCase` => `inputCrosswordExampleName`

**Comment by JetBrain2056** [comment]
fixed 'input-confirmpass'
